### ISSUE TITLE
Cvar for dead players informer

### ISSUE THREAD

**Issue by Nord1cWarr1or** [OciXCrom/RankSystem#3]
Please make the setting for hud position for dead players, because now I set my informer on 
the top of screen, and if I watch for alive player, it is hidden by black line of default HUD cs 1.6

**Comment by OciXCrom** [comment]
You can use the `HUD_POSITION` setting to move it down a bit for both dead and alive players. There won't be any noticeable difference for alive players, but it can help for dead ones. I'll have in mind adding a separate position for dead players in the next update.

**Comment by Nord1cWarr1or** [comment]
> There won't be any noticeable difference for alive players
but i need it right on the top of screen)

> I'll have in mind adding a separate position for dead players in the next update.
ok, thanks

**Comment by OciXCrom** [comment]
@Nord1cWarr1or I added a HUDINFO_POSITION_DEAD setting in the new update.
