### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by herbagen1** [OciXCrom/RankSystem#5]
Hi!! This plugin it's no working to my server. Please sloved me 🙏🙏

Thanks!

**Comment by OciXCrom** [comment]
Please provide information so I can help you. What did you do and what's the problem? Are you aware of how to install plugins?

**Comment by herbagen1** [comment]
I know how to install a plugin, but it doesn't run on my server. gives error in server console. can you help me with an .amxx and .sma + the rest for an optimal installation? at .sma gave compilation error the first time. This erorr appear in console:

[AMXX] Load error 17 (invalid file format or version) (plugin "crx_ranksystem.amxx")

**Comment by herbagen1** [comment]
Help me to link complete plugin??? Please...

**Comment by OciXCrom** [comment]
Compile the plugin locally. Don't use online compilers. Compile under the same AMXX version that your server is using.
